# Generated by Django 4.1.3 on 2023-05-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0010_alter_item_qr_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="cat_code",
            field=models.CharField(default="", max_length=20, verbose_name="Код"),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes"),
        ),
    ]
