# Generated by Django 4.1.3 on 2023-05-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0011_alter_category_cat_code_alter_category_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="cat_code",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
