# Generated by Django 4.1.3 on 2023-01-07 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="OutItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("location", models.CharField(max_length=100)),
                ("requestor", models.CharField(max_length=100)),
                ("out_date", models.DateTimeField(auto_now=True)),
                ("return_date", models.DateTimeField()),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            models.Q(("app_label", "www"), ("model", "item")),
                            models.Q(("app_label", "www"), ("model", "bulkitem")),
                            models.Q(("app_label", "www"), ("model", "consumable")),
                            models.Q(("app_label", "www"), ("model", "license")),
                            _connector="OR",
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_content_type",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("license_id", models.CharField(max_length=20)),
                ("license_name", models.CharField(max_length=100)),
                ("purchase_cost", models.PositiveIntegerField()),
                ("notification_days", models.PositiveIntegerField()),
                ("licensed_to", models.CharField(max_length=100)),
                ("product_key", models.TextField()),
                ("vendor", models.CharField(blank=True, max_length=100)),
                ("purchased_date", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("order_number", models.CharField(blank=True, max_length=100)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="www.department"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("item_code", models.CharField(max_length=20)),
                ("item_name", models.CharField(max_length=100)),
                ("price", models.PositiveIntegerField()),
                ("location", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("vendor", models.CharField(blank=True, max_length=100)),
                ("date_received", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("order_number", models.CharField(blank=True, max_length=100)),
                ("holder", models.CharField(blank=True, default=None, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("outinuse", "Out In Use"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="www.category"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="www.department"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneratedQRCode",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("qr_code_url", models.CharField(max_length=200)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="www.item"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Consumable",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("items_code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("price", models.PositiveIntegerField()),
                ("total_quantity", models.PositiveIntegerField()),
                ("min_alert_quantity", models.PositiveIntegerField()),
                ("location", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("vendor", models.CharField(blank=True, max_length=100)),
                ("date_received", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("holder", models.CharField(blank=True, default=None, max_length=100)),
                ("order_number", models.CharField(blank=True, max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="www.category"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="www.department"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BulkItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("item_code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("price", models.PositiveIntegerField()),
                ("total_quantity", models.PositiveIntegerField()),
                ("min_alert_quantity", models.PositiveIntegerField()),
                ("location", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("vendor", models.CharField(blank=True, max_length=100)),
                ("date_received", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("order_number", models.CharField(blank=True, max_length=100)),
                ("holder", models.CharField(blank=True, default=None, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("outinuse", "Out In Use"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="www.category"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="www.department"
                    ),
                ),
            ],
        ),
    ]
