# Generated by Django 4.1.3 on 2023-01-13 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_title", models.CharField(max_length=200)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("location", models.CharField(max_length=100)),
                ("requestor", models.CharField(max_length=100)),
                ("check_out_date", models.DateTimeField(auto_now=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="www.category"
                    ),
                ),
                (
                    "check_out_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="www.department"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_id", models.CharField(max_length=20)),
                ("license_name", models.CharField(default="", max_length=100)),
                ("purchase_cost", models.PositiveIntegerField(default=0)),
                ("notification_days", models.PositiveIntegerField(default=3)),
                ("licensed_to", models.CharField(default="", max_length=100)),
                ("product_key", models.TextField(blank=True)),
                ("licensed_by", models.CharField(blank=True, max_length=100)),
                ("purchased_date", models.DateField(null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("order_number", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="www.department"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_code", models.CharField(max_length=100)),
                ("item_name", models.CharField(max_length=300)),
                ("price", models.PositiveIntegerField(default=0)),
                (
                    "currency",
                    models.CharField(blank=True, default="USD", max_length=20),
                ),
                (
                    "location",
                    models.CharField(blank=True, default="storage", max_length=100),
                ),
                (
                    "campus",
                    models.CharField(
                        choices=[
                            ("Naryn", "Naryn"),
                            ("Khorog", "Khorog"),
                            ("Tekeli", "Tekeli"),
                        ],
                        default="Naryn",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("vendor", models.CharField(blank=True, max_length=100)),
                ("date_received", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("order_number", models.CharField(blank=True, max_length=100)),
                ("holder", models.CharField(blank=True, default="", max_length=100)),
                ("qr_code", models.CharField(blank=True, default="", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("outinuse", "Out In Use"),
                            ("broken", "Broken"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="www.category"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="www.department"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Consumable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("items_code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("price_per_unit", models.PositiveIntegerField(default=0)),
                (
                    "currency",
                    models.CharField(blank=True, default="USD", max_length=20),
                ),
                ("total_quantity", models.PositiveIntegerField(default=1)),
                (
                    "quantity_unit",
                    models.CharField(blank=True, default="PCS", max_length=20),
                ),
                ("total_price", models.PositiveIntegerField(default=0)),
                ("min_alert_quantity", models.PositiveIntegerField()),
                (
                    "location",
                    models.CharField(blank=True, default="storage", max_length=100),
                ),
                ("description", models.TextField(blank=True)),
                ("vendor", models.CharField(blank=True, max_length=100)),
                ("date_received", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("holder", models.CharField(blank=True, default=None, max_length=100)),
                ("qr_code", models.CharField(blank=True, default="", max_length=200)),
                ("order_number", models.CharField(blank=True, max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="www.category"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="www.department"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BulkItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=300)),
                ("price_per_unit", models.PositiveIntegerField(default=0)),
                (
                    "currency",
                    models.CharField(blank=True, default="USD", max_length=20),
                ),
                ("total_quantity", models.PositiveIntegerField(default=1)),
                (
                    "quantity_unit",
                    models.CharField(blank=True, default="PCS", max_length=20),
                ),
                ("total_price", models.PositiveIntegerField(default=0)),
                ("min_alert_quantity", models.PositiveIntegerField()),
                (
                    "location",
                    models.CharField(blank=True, default="storage", max_length=100),
                ),
                ("description", models.TextField(blank=True)),
                ("vendor", models.CharField(blank=True, max_length=100)),
                ("date_received", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("order_number", models.CharField(blank=True, max_length=100)),
                ("qr_code", models.CharField(blank=True, default="", max_length=200)),
                ("holder", models.CharField(blank=True, default="", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("outinuse", "Out In Use"),
                            ("broken", "Broken"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="www.category"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="www.department"
                    ),
                ),
            ],
        ),
    ]
