# Generated by Django 4.1.3 on 2023-01-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="campus",
            field=models.CharField(
                choices=[
                    ("Naryn", "Naryn"),
                    ("Khorog", "Khorog"),
                    ("Tekeli", "Tekeli"),
                ],
                default="Naryn",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="currency",
            field=models.CharField(blank=True, default="USD", max_length=20),
        ),
        migrations.AlterField(
            model_name="bulkitem",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_code",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_name",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="item",
            name="location",
            field=models.CharField(blank=True, default="storage", max_length=100),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[("available", "Available"), ("outinuse", "Out In Use")],
                default="available",
                max_length=20,
            ),
        ),
    ]
