# Generated by Django 4.1.3 on 2023-01-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="items"),
        ),
        migrations.AlterField(
            model_name="consumable",
            name="holder",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
