# Generated by Django 4.1.3 on 2022-12-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_qrcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QrCode',
        ),
    ]
