# Generated by Django 4.1.3 on 2023-01-07 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0002_item_campus_item_currency_alter_bulkitem_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="outitem",
            old_name="content_type",
            new_name="item_type",
        ),
    ]
