# Generated by Django 4.1.3 on 2023-01-07 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0003_rename_content_type_outitem_item_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkItemOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("requestor", models.CharField(max_length=100)),
                ("out_date", models.DateTimeField(auto_now=True)),
                ("return_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConsumableOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("requestor", models.CharField(max_length=100)),
                ("out_date", models.DateTimeField(auto_now=True)),
                ("return_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ItemOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("requestor", models.CharField(max_length=100)),
                ("out_date", models.DateTimeField(auto_now=True)),
                ("return_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="bulkitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="consumable",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(
            name="OutItem",
        ),
        migrations.AddField(
            model_name="itemout",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="www.item"
            ),
        ),
        migrations.AddField(
            model_name="consumableout",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="www.consumable"
            ),
        ),
        migrations.AddField(
            model_name="bulkitemout",
            name="items",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="www.bulkitem"
            ),
        ),
    ]
