# Generated by Django 4.1.3 on 2022-12-25 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_delete_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='qr_code_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
