# Generated by Django 4.1.3 on 2023-02-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0003_item_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="cat_code",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="department",
            name="dep_code",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="item",
            name="campus",
            field=models.CharField(
                choices=[("NAR", "Naryn"), ("KHG", "Khorog"), ("TKL", "Tekeli")],
                default="Naryn",
                max_length=20,
            ),
        ),
    ]
