# Generated by Django 4.1.3 on 2023-01-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0003_bulkitem_image_consumable_image_alter_item_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bulkitem",
            old_name="name",
            new_name="item_name",
        ),
        migrations.RenameField(
            model_name="consumable",
            old_name="name",
            new_name="item_name",
        ),
    ]
