# Generated by Django 4.1.3 on 2022-12-25 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_item_qr_code_url_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='qr_code_url',
        ),
        migrations.CreateModel(
            name='GeberatedQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_url', models.CharField(max_length=200)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='www.item')),
            ],
        ),
    ]
