# Generated by Django 4.1.3 on 2023-01-07 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("www", "0004_bulkitemout_consumableout_itemout_alter_bulkitem_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_title", models.CharField(max_length=200)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("location", models.CharField(max_length=100)),
                ("requestor", models.CharField(max_length=100)),
                ("check_out_date", models.DateTimeField(auto_now=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="www.category"
                    ),
                ),
                (
                    "check_out_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="www.department"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="consumableout",
            name="item",
        ),
        migrations.RemoveField(
            model_name="generatedqrcode",
            name="item",
        ),
        migrations.RemoveField(
            model_name="itemout",
            name="item",
        ),
        migrations.AddField(
            model_name="item",
            name="qr_code",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="item",
            name="holder",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.DeleteModel(
            name="BulkItemOut",
        ),
        migrations.DeleteModel(
            name="ConsumableOut",
        ),
        migrations.DeleteModel(
            name="GeneratedQRCode",
        ),
        migrations.DeleteModel(
            name="ItemOut",
        ),
    ]
