# Generated by Django 4.1.3 on 2023-01-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0005_loan_remove_consumableout_item_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bulkitem",
            old_name="price",
            new_name="price_per_unit",
        ),
        migrations.RenameField(
            model_name="license",
            old_name="vendor",
            new_name="licensed_by",
        ),
        migrations.RemoveField(
            model_name="bulkitem",
            name="name",
        ),
        migrations.RemoveField(
            model_name="consumable",
            name="price",
        ),
        migrations.AddField(
            model_name="bulkitem",
            name="qr_code",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="bulkitem",
            name="quantity_unit",
            field=models.CharField(default="PCS", max_length=20),
        ),
        migrations.AddField(
            model_name="bulkitem",
            name="total_price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="consumable",
            name="price_per_unit",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="consumable",
            name="qr_code",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="consumable",
            name="quantity_unit",
            field=models.CharField(default="PCS", max_length=20),
        ),
        migrations.AddField(
            model_name="consumable",
            name="total_price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bulkitem",
            name="total_quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="consumable",
            name="total_quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
